baseURL = 'https://qiuqiu.qqviaja.com/'
languageCode = 'en-us'
title = 'Qiuqiu'
theme = 'cloudflare-gallery'

[outputs]
  home = ["HTML", "RSS", "JSON"]  # Output formats for the homepage
  page = ["HTML", "JSON"] 

[params]
  placeholderImage = "/images/placeholder.jpg"  # Optional
  googleAdsense = "5748363844796033"

[params.cloudflareImages]
  workerURL = "https://worker-gallery.qqviaja.com/images-api/"
  accountHash = "W_2keQlBhLiZqemRqewoUA"
  accountID = "2796216706dc27857293e665688e4acb"

[[menu.main]]
    identifier = "photos"  
    name = "Photos"        
    url = "/"             # Changed to root URL "/" to make it the index/home page
    weight = 1            # Set to 1 to ensure it appears first in navigation

[build]
  writeStats = true
  
[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^hugo$"]
  [security.funcs]
    getenv = ["^HUGO_"]